"""Allow rating to be NULL in movies

Revision ID: 74ea4518d2df
Revises: a711268d83b0
Create Date: 2024-07-28 15:10:56.000478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74ea4518d2df'
down_revision: Union[str, None] = 'a711268d83b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'rating', existing_type=sa.Float(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'rating', existing_type=sa.Float(), nullable=False)
    # ### end Alembic commands ###
